site_name: finance_forecaster
site_description: "Finance Forecasting ML Model Pipeline -- Predicting Next Day Financial Movements"
site_author: "Finance Forecasters"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc
